name: typeweight
description: Library to help you to use more readable font weight definitions in Flutter.
version: 2.0.2
repository: https://github.com/frencojobs/typeweight

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  test: ^1.22.0
